apiVersion: apps/v1
kind: StatefulSet  # Ver de pasarlo a operador de mysql para poder aumentar el numero de replicas de mejor forma
metadata:
  name: db-kube
spec:
  serviceName: db-kube
  replicas: 1 
  selector:
    matchLabels:
      app: db-kube
  template:
    metadata:
      labels:
        app: db-kube
    spec: 
      containers:
        - name: db
          image: mysql/mysql-server:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_ROOT_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-enviroment-varaibles
                  key: MYSQL_ROOT_HOST
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-enviroment-varaibles
                  key: MYSQL_DATABASE
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: host-pvc
            