name: Deploy API on push

on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        registry: ${{ secrets.DHR_URL }} 
        username: ${{ secrets.DHR_UN }}
        password: ${{ secrets.DHR_PASS }}
        logour: true

    - name: Build and push the Docker image
      run: |
        docker build --file Dockerfile --tag ${{ secrets.DHR_URL }}/api-test-kube:$ {{ github.sha }} ./API/app/.
        docker push ${{ secrets.DHR_URL }}/api-test-kube:$ {{ github.sha }}
        
    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
