name: Deploy API on push

on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DHR_UN }}
        password: ${{ secrets.DHR_PASS }}

    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        
    - name: Build and push the Docker image
      run: |
        docker build --tag api-test-kube:${{ github.sha }} ./API/app/.
        docker push api-test-kube:${{ github.sha }}
    #    kubectl apply -f Kubernetes/deployment-api.yaml
        
    
        
    
